apiVersion: v1
kind: Pod
metadata:
  name: api-simples
  labels:
    app: api-simples
spec:
  containers:
  - name: api-simples
    image: dudures/api-simples:1.0.0
    ports:
    - containerPort: 3000