apiVersion: v1
kind: Service
metadata:
  name: api-simples
  labels:
    app: api-simples
spec:
  #type: ClusterIP
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    #nodePort: 30007
  selector:
    app: api-simples 